name: 🐛 Issue Report
description: Report a bug, broken link, or issue with the awesome-sovereign list
title: "[ISSUE] "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report an issue with Awesome Sovereign Cloud! Please fill out the form below to help us understand and resolve the problem.

  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      description: What type of issue are you reporting?
      options:
        - Broken link
        - Incorrect information
        - Missing information
        - Formatting issue
        - Categorization issue
        - Other
    validations:
      required: true

  - type: dropdown
    id: section
    attributes:
      label: Section
      description: Which section is affected?
      options:
        - Cloud Providers
        - Infrastructure as Code
        - Container Platforms
        - Kubernetes Distributions
        - Edge Computing
        - Storage Solutions
        - Networking
        - Security & Privacy
        - Monitoring & Observability
        - Development Tools
        - AI/ML Platforms
        - Data & Analytics
        - Identity & Access Management
        - Communication & Collaboration
        - Ecosystem Organizations
        - Standards & Frameworks
        - Learning Resources
        - News & Updates
        - Other/Unknown
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please provide a clear and concise description of the issue
      placeholder: Describe the issue you encountered...
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe what you expected to see or happen...

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened...

  - type: input
    id: affected-url
    attributes:
      label: Affected URL/Link
      description: If this is a broken link, please provide the URL
      placeholder: https://example.com

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Any additional information that might be helpful...

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have verified that this is an issue with the awesome-sovereign list
          required: true
        - label: I have provided all the requested information
          required: true

  - type: markdown
    attributes:
      value: |
        ## 📋 Additional Information

        If you have any additional information, screenshots, or context that might help us resolve this issue, please include it below.

        Thank you for helping improve Awesome Sovereign Cloud! 🚀
